DROP TABLE IF EXISTS askify_questions;

CREATE TABLE askify_questions (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        title TEXT NOT NULL,
        body TEXT NOT NULL,
        tags TEXT [],
        date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);