DROP TABLE IF EXISTS askify_users;

CREATE TABLE askify_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    password TEXT NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
    date_modified TIMESTAMPTZ
);

ALTER TABLE askify_questions
ADD COLUMN
   user_id INTEGER REFERENCES askify_users(id)
    ON DELETE SET NULL;