DROP TABLE IF EXISTS askify_answers;

CREATE TABLE askify_answers (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    answer TEXT NOT NULL,
    votes INTEGER NOT NULL DEFAULT '0',
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
    question_id INTEGER
        REFERENCES askify_questions(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER
        REFERENCES askify_users(id) ON DELETE CASCADE NOT NULL
);